### ISSUE TITLE
Initial Release TODO

### ISSUE THREAD

**Issue by IntegerLimit** [IntegerLimit/StorageDrawers-1.12.2-dev#3]
- [ ] Perhaps Native Hand Framing Tool + Native Hand Framing Recipes (use code from https://github.com/Nomi-CEu/nomi-ceu/tree/groovy)
- [ ] Some way to destroy drawers, and drop items, when the drop drawers with items config is on. Perhaps Destruction Tape? 
- [x] Config to make framing table not consume blocks
- [ ] If that tape is implemented, make it so that it contradicts packaging tape
- [ ] Tape Remover?
- [x] Native TOP fixes, move the TOP fixes from https://github.com/Nomi-CEu/gregtech-drawers
- [ ] Other stuff in https://github.com/Nomi-CEu/StorageDrawers/milestone/1

**Comment by IntegerLimit** [comment]
Native TOP Fixes & more done in https://github.com/IntegerLimit/StorageDrawers-1.12.2-dev/tree/rfg-edition-fix-integrations.

**Comment by IntegerLimit** [comment]
A lot of bug fixes have occurred. An initial, mostly bug fixing release, will be deployed soon.

**Comment by a-a-GiTHuB-a-a** [comment]
What would the Destruction Tape recipe be?
